language: go
go:
  - 1.6
  - tip
os:
  - linux
  - osx
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
install:
  - go get -v ./...
script:
  - ./coverage.sh --coveralls